---
title: "Measuring Gentrification - A Study in Boston"
author: "Xiayuanshan Gao"
date: "2024-05-07"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: yes
    theme: cosmo 
    highlight: tango    
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(RColorBrewer)
library(RSocrata)

library(RSocrata)
library(viridis)
library(spatstat)
library(spdep)
library(FNN)
library(knitr)
library(kableExtra)
library(tidycensus)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#7892B5","#8CB9C0","#91B5A9","#EDCA7F","#D98481")
palette4 <- c("#7892B5","#8CB9C0","#EDCA7F","#D98481")
palette2 <- c("#7892B5","#D98481")

```

# Intro


# Data Collection



## boundary

```{r load}

# Reading neighborhood boundaries GeoJSON from the raw GitHub URL and transforming CRS
boundary <- st_read(url("https://raw.githubusercontent.com/XiaysG/PPA_Final/CityBoundaryofLosAngeles.geojson"))
```


## Spatial Data

```{r}
# Bike Share Station

blueBikesStation <- read.csv("https://bostonopendata-boston.opendata.arcgis.com/api/download/v1/items/14cc9c330fe641d2ae1bd3b7c29d5008/csv?layers=0", stringsAsFactors = FALSE)

blueBikesStation <- blueBikesStation %>%
  na.omit() %>%
  dplyr::select(Y = Latitude, X = Longitude) %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102286')
```

```{r}
busStation <- st_read("https://LA-METRO.maps.arcgis.com/apps/Minimalist/index.html?appid=1fd006edf4cc446cad245c72241afba5") %>%
  st_transform('ESRI:102645')
```

```{r}
metro <- 
  st_read("https://public.gis.lacounty.gov/public/rest/services/LACounty_Dynamic/LMS_Data_Public/MapServer/185/query?outFields=*&where=1%3D1&f=geojson")
  metro <- metro %>%
  na.omit() %>%
  dplyr::select(Y = latitude, X = longitude) %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102645')
```
## Grocery store
```{r}
grocerystore <- read.socrata("https://data.lacity.org/resource/g986-7yf9.json")

# Clean and process the data
grocerystore <- grocerystore %>%
  na.omit() %>%
  dplyr::select(location_1.latitude, location_1.longitude) %>%
  st_as_sf(coords = c("location_1.longitude", "location_1.latitude"), crs = 4326, agr = "constant")%>%
 st_transform('ESRI:102645')
```

```{r}
# Read new housing permit data
newhousingpermit <- read.socrata("https://data.lacity.org/resource/5u9x-y4iz.json")

# Clean and process the data
newhousingpermit <- newhousingpermit %>%
  dplyr::select(Y = location_1.latitude, X = location_1.longitude) %>%
  na.omit()%>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")
  
```

```{r}
restaurant <- read.socrata("https://data.lacity.org/resource/ieer-tbdq.json")

restaurant <- restaurant %>%
  dplyr::select(Y = location_1.latitude, X = location_1.longitude) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")  # Transforming to the specified CRS

```

```{r}
educationfacities <- 
 st_read("https://services.arcgis.com/RmCCgQtiZLDCtblq/arcgis/rest/services/Schools_Colleges_and_Universities/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson") 

educationfacities <- educationfacities %>%
dplyr::select(Y = latitude, X = longitude) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")  # Transforming to the specified CRS

```

```{r}
# income restricted housing by neighborhood

inc_restricted_housing_2022 <- read.csv("https://data.boston.gov/dataset/feddfe5a-df16-4c60-8a3c-640c4d5281cd/resource/bfdeffc7-ab5e-4e28-9561-d4e84c9674e4/download/income-restricted-housing-inventory-2022.csv", stringsAsFactors = FALSE)

inc_restricted_housing_2018 <- read.csv("https://data.boston.gov/dataset/feddfe5a-df16-4c60-8a3c-640c4d5281cd/resource/47d53d7c-25b7-40b4-9259-da1d15373be6/download/income-restricted-inventory-2018-all-income-restricted-projects.csv", stringsAsFactors = FALSE)

```


## Census Data 2015 and 2020

```{r}

census_api_key("f681592f0e7bc7e399e41102649c493ec7f7f574") 

variables <- c("B01001_001E",
  "B01001_002E",
  "B01001_026E",
   "B01001_007E",
  "B01001_012E",
   "B01001_016E",
 "B01001_020E","B02001_002E","B02001_003E", "B03001_003E", "B02001_004E", "B19001_002E","B19001_003E", "B19001_006E", "B19001_008E",
"B19001_010E", "B19001_012E","B07001_001E","B07001_017E","B07001_033E",
"B07001_049E",
"B07001_065E",
  "B15001_002E",
 "B15001_003E",
"B15001_005E",
"B15001_009E",
"B15001_010E",
   "B25001_001E",
  "B06012_002E",
  "B25002_003E",
"B25006_002E",
  "B25006_001E",
  "B19013_001E",
"B25077_001E",
"B25031_001",
"B08133_001"
)



# Fetch the data for LA, LA County, CA,2015
acs_la <- get_acs(
  geography = "tract",
  variables = variables,
  year = 2015,
  state = "06",
  county = "037",
  geometry = TRUE,
  survey = "acs5",
  output = "wide"
)%>%
st_transform('ESRI:102645')



# Fetch the data for LA, LA County, CA,2020
acs_la20 <- get_acs(
  geography = "tract",
  variables = variables,
  year = 2020,
  state = "06",
  county = "037",
  geometry = TRUE,
  survey = "acs5",
  output = "wide"
)%>%
  st_transform('ESRI:102645')
vars <- load_variables(2020, "acs5", cache = TRUE)

```


```{r}
# Load necessary libraries
library(dplyr)
library(sf)  # for spatial operations like st_area()

# Assuming acs_la is already an sf object with proper geometry handling
acs_la <- acs_la %>%
  rename(
    totalPop = B01001_001E,
    male = B01001_002E,
    female = B01001_026E,
    age_18_24 = B01001_007E,
    age_25_44 = B01001_012E,
    age_45_64 = B01001_016E,
    age_65plus = B01001_020E,
    white = B02001_002E,
    popblack = B02001_003E,
    latino = B03001_003E,
    other_race = B02001_004E,
    income_less_20k = B19001_002E,
    income_20k_40k = B19001_003E,
    income_40k_60k = B19001_006E,
    income_60k_80k = B19001_008E,
    income_80k_100k = B19001_010E,
    income_more_100k = B19001_012E,
    migration_total = B07001_001E,
    migration_within_county = B07001_017E,
    migration_different_county_same_state = B07001_033E,
    migration_different_state = B07001_049E,
    migration_from_abroad = B07001_065E,
    edu_less_high_school = B15001_002E,
    edu_high_school_grad = B15001_003E,
    edu_some_college = B15001_005E,
    edu_bachelors = B15001_009E,
    edu_grad_professional = B15001_010E,
    total_housing_units = B25001_001E,
    total_poverty = B06012_002E,
    vacant_units = B25002_003E,
    white_houseOwner = B25006_002E,
    total_occupied_units = B25006_001E,
    median_HH_income = B19013_001E,
    houseprice = B25077_001E,
    rent = B25031_001E,
    travetimetowork = B08133_001E
  ) %>%
  select(-starts_with("B"),-GEOID,-NAME) %>%
  mutate(
    WhiteHOrate = white_houseOwner / total_occupied_units,
    pctBachelors = ifelse(totalPop > 0, (edu_bachelors + edu_grad_professional) / totalPop, 0),
    pctPoverty = ifelse(totalPop > 0, total_poverty / totalPop, 0),
    pctWhitePop = ifelse(totalPop > 0, white / totalPop, 0),
    pctLatinoPop = ifelse(totalPop > 0, latino / totalPop, 0),
    pctBlackPop = ifelse(totalPop > 0, popblack / totalPop, 0),
    pctMigration = ifelse(totalPop > 0, migration_total / totalPop, 0),
    pctForeignMig = ifelse(totalPop > 0, migration_from_abroad / totalPop, 0),
    landArea = st_area(geometry),  # Ensure this is the correct function for your spatial data
    popDensity = totalPop / as.numeric(landArea)
  )

```

```{r}
acs_la20 <- acs_la20 %>%
  rename(totalPop20 = "B01001_001E",
  male20 = "B01001_002E",
  female20 = "B01001_026E",
  age_18_2420 = "B01001_007E",
  age_25_4420 = "B01001_012E",
  age_45_6420 = "B01001_016E",
  age_65plus20 = "B01001_020E",
  white20 = "B02001_002E",
  popblack20 = "B02001_003E",
  latino20 = "B03001_003E",
  other_race20 = "B02001_004E",
  income_less_20k20 = "B19001_002E",
  income_20k_40k20 = "B19001_003E",
  income_40k_60k20 = "B19001_006E",
  income_60k_80k20 = "B19001_008E",
  income_80k_100k20 = "B19001_010E",
  income_more_100k20 = "B19001_012E",
  migration_total20 = "B07001_001E",
  migration_within_county20 = "B07001_017E",
  migration_different_county_same_state20 = "B07001_033E",
  migration_different_state20 = "B07001_049E",
  migration_from_abroad20 = "B07001_065E",
  edu_less_high_school20 = "B15001_002E",
  edu_high_school_grad20 = "B15001_003E",
  edu_some_college20 = "B15001_005E",
  edu_bachelors20 = "B15001_009E",
  edu_grad_professional20 = "B15001_010E",
  total_housing_units20 = "B25001_001E",
  total_poverty20 = "B06012_002E",
  vacant_units20 = "B25002_003E",
  white_houseOwner20 = "B25006_002E",
  total_Ooccupied_Uunits20 = "B25006_001E",
  median_HH_income20 = "B19013_001E",
  houseprice20 = "B25077_001E",
  rent20="B25031_001E",
  travetimetowork20 = B08133_001E
)%>%
  dplyr::select(-starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(WhiteHOrate20 = white_houseOwner20/total_Ooccupied_Uunits20,
         pctBachelors20 = ifelse(totalPop20 > 0, ((edu_bachelors20 + edu_grad_professional20) / totalPop20),0),
         pctPoverty20 = ifelse(totalPop20 > 0, total_poverty20 / totalPop20, 0),
         pctWhitePop20 = ifelse(totalPop20 > 0, white20 / totalPop20, 0),
         pctLatinoPop20 = ifelse(totalPop20 > 0, latino20 / totalPop20, 0),
         pctBlackPop20 = ifelse(totalPop20 > 0, popblack20 / totalPop20, 0),
         pctMigration20 = ifelse(totalPop20 > 0, migration_total20 / totalPop20, 0),
         pctForeignMig20 = ifelse(totalPop20 > 0, migration_from_abroad20 / totalPop20, 0),
         landArea20 = st_area(geometry), 
         popDensity20 = totalPop20 / as.numeric(landArea20))
```

```{r}
# Drop Margin Columns from ACS
data<-st_join(acs_la,acs_la20)
boundary <- st_transform(boundary, crs = st_crs(data))
dataclipped <- st_intersection(data, boundary)

```




# Measuring Gentrification

```{r}

```

## 


# Methodolody
logistic regression

# Feature Engineering

## identify number of grocery stores in each tract
```{r}
joined_data <- st_join(tracts, grocerystore, join = st_within)
restaurant_count <- joined_data %>%
  group_by(TRACT_ID) %>%  # Replace TRACT_ID with the actual identifier field for tracts
  summarise(Count = n())
```

## identify grocery store coverage
```{r}
store_buffer<- rbind(
  st_buffer(grocerystore,2640) %>%
    mutate(Legend = 'buffer')%>%
    dplyr::select(Legend),
  st_union(st_buffer(grocerystore,2640))%>%
    st_sf()%>%
    mutate(Legend = 'Unioned Buffer'))
```



# Conclusion










